version: '3.8'

services:
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - phantom-net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - app_code:/opt/phantom-identity
    ports:
      - target: 3000
        published: 3001
        protocol: tcp
        mode: ingress
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - CORS_ORIGIN=*
      - LOG_LEVEL=info
    networks:
      - phantom-net
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
        preferences:
          - spread: node.id
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 1G
          cpus: '0.8'
        reservations:
          memory: 512M
          cpus: '0.4'
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
    command: >
      sh -c "
        cd /app &&
        npm install --production --silent &&
        npm start
      "
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 120s

  # Visualizer para monitorar o Swarm
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - phantom-net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 128M
          cpus: '0.2'

volumes:
  redis_data:
    driver: local
  app_code:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/phantom-identity

networks:
  phantom-net:
    driver: overlay
    attachable: true
    driver_opts:
      encrypted: "true" 